version: '2'
services:

  # The Application
  app:
    command: composer install
    build:
      context: ./
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "host=localhost"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes_from:
      - app
    links:
      - app
    ports:
      - 8091:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=test_form"
      - "MYSQL_USER=test-form"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33062:3306"

volumes:
  db: