version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "host=localhost"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes_from:
      - app
    links:
      - app
    ports:
      - 8091:80

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes_from:
      - app
    working_dir: /var/www

  node:
    image: "node:8"
    working_dir: /var/www
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www
    expose:
      - "8091"
    command: bash -c "chmod -R u+x . && npm install standard@10.0.3 -g cross-env@latest style-loader --save-dev && npm run development"

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=test_form"
      - "MYSQL_USER=test-form"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33062:3306"

volumes:
  db:
